import {
    MAKE_LOGIN,
    MAKE_LOGIN_ERROR,
    MAKE_LOGOUT,
    MAKE_LOGOUT_ERROR,
    SET_TOKEN,
    RESET_AUTH_ERROR
} from './authTypes'
import {
    MAKE_SIGNUP,
    MAKE_SIGNUP_ERROR,
    RESET_SIGNUP_ERROR
} from './signUpTypes'

import {
    GET_MY_RECIPES,
    GET_MY_RECIPES_ERROR,
    ADD_RECIPE,
    ADD_RECIPE_ERROR,
    UPDATE_RECIPES_LIST,
    UPDATE_PAGE
} from './recipeTypes'


const RESET_STORE = 'RESET_STORE'

export {
    MAKE_LOGIN,
    MAKE_LOGIN_ERROR,
    MAKE_LOGOUT,
    MAKE_LOGOUT_ERROR,
    SET_TOKEN,
    RESET_AUTH_ERROR,
    MAKE_SIGNUP,
    MAKE_SIGNUP_ERROR,
    RESET_SIGNUP_ERROR,
    GET_MY_RECIPES,
    GET_MY_RECIPES_ERROR,
    ADD_RECIPE,
    ADD_RECIPE_ERROR,
    UPDATE_RECIPES_LIST,
    UPDATE_PAGE,
    RESET_STORE
}