import {
    MAKE_LOGIN,
    MAKE_LOGIN_ERROR,
    MAKE_LOGOUT,
    MAKE_LOGOUT_ERROR,
    SET_TOKEN,
    RESET_AUTH_ERROR
} from './authTypes'
import {
    MAKE_SIGNUP,
    MAKE_SIGNUP_ERROR,
    RESET_SIGNUP_ERROR
} from './signUpTypes'

export {
    MAKE_LOGIN,
    MAKE_LOGIN_ERROR,
    MAKE_LOGOUT,
    MAKE_LOGOUT_ERROR,
    SET_TOKEN,
    RESET_AUTH_ERROR,
    MAKE_SIGNUP,
    MAKE_SIGNUP_ERROR,
    RESET_SIGNUP_ERROR
}